name: task_management_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  ionicons: 0.1.2
  firebase_core: ^1.20.0
  firebase_core_web: ^1.7.0
  firebase_auth: ^3.5.1
  google_sign_in: 5.4.0
  cloud_firestore: 3.4.3
  date_time_picker: 2.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/Images/
    - assets/Icons/
  uses-material-design: true

