// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzJQBufGKw79q8qKvTlvALWQsAREaOuxM',
    appId: '1:481957066360:web:be3e2593b85ae8aa8c5f8d',
    messagingSenderId: '481957066360',
    projectId: 'task-management-app-f2c8a',
    authDomain: 'task-management-app-f2c8a.firebaseapp.com',
    storageBucket: 'task-management-app-f2c8a.appspot.com',
    measurementId: 'G-25MQDJ1F8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC33_HC0DcWiHZkYKuFD93KUCzTBICyMU0',
    appId: '1:481957066360:android:90d7eb9bb08ca9b08c5f8d',
    messagingSenderId: '481957066360',
    projectId: 'task-management-app-f2c8a',
    storageBucket: 'task-management-app-f2c8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPiayUJZlK8VOOU2-eqLXznfQFT-IEcYg',
    appId: '1:481957066360:ios:036bd55f3c3ff5308c5f8d',
    messagingSenderId: '481957066360',
    projectId: 'task-management-app-f2c8a',
    storageBucket: 'task-management-app-f2c8a.appspot.com',
    androidClientId: '481957066360-cgqsi6cts63t3kn4le0rbiecaulnok7g.apps.googleusercontent.com',
    iosClientId: '481957066360-lckpn6f31o38h3mobmn4an81o8ccmn39.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPiayUJZlK8VOOU2-eqLXznfQFT-IEcYg',
    appId: '1:481957066360:ios:036bd55f3c3ff5308c5f8d',
    messagingSenderId: '481957066360',
    projectId: 'task-management-app-f2c8a',
    storageBucket: 'task-management-app-f2c8a.appspot.com',
    androidClientId: '481957066360-cgqsi6cts63t3kn4le0rbiecaulnok7g.apps.googleusercontent.com',
    iosClientId: '481957066360-lckpn6f31o38h3mobmn4an81o8ccmn39.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );
}
